# Dependencies
markdown: rdiscount
pygments: true

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Setup
title: polovko.me
tagline: 'Заметки на полях'
description: >
    "И тут Остапа понесло..." &copy; Ильф и Петров
url: http://www.polovko.me

author:
  name: 'Sergey Polovko'
  email: sergey@polovko.me

paginate: 5

# Custom vars
github: https://github.com/jamel
twitter: https://twitter.com/the_jamel
readmore_link: 'Читать дальше &rarr;'
